development:
  adapter: postgresql
  database: wikiful_development
  encoding: unicode
  user: postgres
  password: password
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: wikiful_test
  encoding: unicode
  user: postgres
  password: password
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: wikiful_production
  encoding: unicode
  pool: 5
  timeout: 5000